name: Windows tests
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        shell: [powershell, pwsh]
    name: Windows / ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v4
      - name: Test in Windows PowerShell
        if: matrix.shell == 'powershell'
        shell: powershell
        run: ./tests/Run-Tests.ps1
      - name: Test in PowerShell 7
        if: matrix.shell == 'pwsh'
        shell: pwsh
        run: ./tests/Run-Tests.ps1
